### ISSUE TITLE
 Error: Command failed: host -a 192.168.23.220

### ISSUE THREAD

**Issue by hktalent** [npm/security-holder#4]
mac os 10.11.6

 Error: Command failed: host -a 192.168.23.220

```
  at ChildProcess.exithandler (child_process.js:206:12)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at maybeClose (internal/child_process.js:877:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
killed: false,
code: 1,
signal: null,
cmd: 'host -a 192.168.23.220'
```

**Comment by BurtHarris** [comment]
@hktalent: What package were you intending to file this issue against?
